/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main_pre.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jihuhwan <jihuhwan@student2seoul.kr>     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/06/09 10:49:18 by jihuhwan          #+#    #+#             */
/*   Updated: 2021/06/09 21:17:53 by jihuhwan         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#include "ft_printf.h"

void    ft_setting(inform_list *inform, va_list ap, char *buf)
{
    inform->width = ft_width(buf, ap, inform);
    inform->precision = ft_precision(buf, ap, inform);
    inform->num = ft_num(ap);
    inform->num_len = ft_int_length(inform->num);
    if (inform->width < 0)
            inform->width *= -1;
}

int    ft_int_main(va_list ap, inform_list *inform, char *str)
{
    char *buf;
    char *res;
    int i;
    int len;

    i = 0;
    buf = ft_strdup(str);
    ft_init(inform);
    len = inform->res_len;
    while (buf[i] != '%' && buf[i] != '\0')
        write(1,&buf[i++],1);
    i++;
    i = ft_flag(i, buf, inform);
    ft_setting(inform,ap,&buf[i]);
    if (inform->num == 0)
        ft_zero_printf(&res,inform);
    else
    {
        if (inform->is_dot == 1)
            ft_ignore_zero(&res,inform);
        else
            ft_zero_minus(&res,inform);
    }
    ft_write(res);
    len += ft_strlen(res);
    i = ft_forward(buf, i);
    free(inform);
    free(res);
    while (buf[i] != '%' && buf[i] != '\0')
        write(1,&buf[i++],1);
    free(buf);
    return(len);
}

void    ft_type(inform_list *inform, char *str)
{
    int i;

    i = 0;
    while (str[i])
    {
        if (str[i] == 'd')
            inform->type = 1;
        else if (str[i] == 'c')
            inform->type = 2;
        else if (str[i] == 's')
            inform->type = 2;
        i++;
    }
}

int    ft_select(inform_list *inform, va_list ap, char *str)
{
    ft_type(inform,str);
    if (inform->type == 1)
        return (ft_int_main(ap,inform,str));
}

int     ft_printf(const char *str, ...)
{
    va_list ap;
    inform_list *inform;
    int result;

    inform = (inform_list *)(malloc)(sizeof(inform_list));
    va_start(ap,str);
    result = ft_select(inform,ap,(char *)str);
    va_end(ap);
    return (result);
}
        // printf("width : %d\n", inform->width);
        // printf("preci : %d\n", inform->precision);
        // printf("num : %d\n", inform->num);
        // printf("length : %d\n", inform->num_len);
        // printf("dot : %d\n", inform->is_dot);
        // printf("zero : %d\n", inform->zero_flag);
        // printf("minus : %d\n", inform->minus_flag);

int main()
{
    int d;
    int num1;
    int num2;

    d = 135;
    num1 = printf(">%-4.d<\n",d);
    num2 = ft_printf(">%-4.d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.*d<\n",6,d);
    num2 = ft_printf(">%-4.*d<\n",6,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.1d<\n",d);
    num2 = ft_printf(">%-4.1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.2d<\n",d);
    num2 = ft_printf(">%-4.2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.3d<\n",d);
    num2 = ft_printf(">%-4.3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.4d<\n",d);
    num2 = ft_printf(">%-4.4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4d<\n",d);
    num2 = ft_printf(">%-4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.d<\n",d);
    num2 = ft_printf(">%-3.d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.*d<\n",6,d);
    num2 = ft_printf(">%-3.*d<\n",6,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.1d<\n",d);
    num2 = ft_printf(">%-3.1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.2d<\n",d);
    num2 = ft_printf(">%-3.2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.3d<\n",d);
    num2 = ft_printf(">%-3.3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.4d<\n",d);
    num2 = ft_printf(">%-3.4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3d<\n",d);
    num2 = ft_printf(">%-3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.d<\n",d);
    num2 = ft_printf(">%-2.d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.*d<\n",6,d);
    num2 = ft_printf(">%-2.*d<\n",6,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.1d<\n",d);
    num2 = ft_printf(">%-2.1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.2d<\n",d);
    num2 = ft_printf(">%-2.2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.3d<\n",d);
    num2 = ft_printf(">%-2.3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.4d<\n",d);
    num2 = ft_printf(">%-2.4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2d<\n",d);
    num2 = ft_printf(">%-2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.d<\n",d);
    num2 = ft_printf(">%-1.d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.*d<\n",6,d);
    num2 = ft_printf(">%-1.*d<\n",6,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.1d<\n",d);
    num2 = ft_printf(">%-1.1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.2d<\n",d);
    num2 = ft_printf(">%-1.2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.3d<\n",d);
    num2 = ft_printf(">%-1.3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.4d<\n",d);
    num2 = ft_printf(">%-1.4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1d<\n",d);
    num2 = ft_printf(">%-1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.d<\n",d);
    num2 = ft_printf(">%.d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.*d<\n",6,d);
    num2 = ft_printf(">%.*d<\n",6,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.1d<\n",d);
    num2 = ft_printf(">%.1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.2d<\n",d);
    num2 = ft_printf(">%.2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.3d<\n",d);
    num2 = ft_printf(">%.3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.4d<\n",d);
    num2 = ft_printf(">%.4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%.0d<\n",d);
    num2 = ft_printf(">%.0d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.d<\n", 10,d);
    num2 = ft_printf(">%*.d<\n", 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.*d<\n",6, 10,d);
    num2 = ft_printf(">%*.*d<\n",6, 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.1d<\n", 10,d);
    num2 = ft_printf(">%*.1d<\n", 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.2d<\n", 10,d);
    num2 = ft_printf(">%*.2d<\n", 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.3d<\n", 10,d);
    num2 = ft_printf(">%*.3d<\n", 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.4d<\n", 10,d);
    num2 = ft_printf(">%*.4d<\n", 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%*.0d<\n", 10,d);
    num2 = ft_printf(">%*.0d<\n", 10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.d<\n", d);
    num2 = ft_printf(">%0.d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.*d<\n",6, d);
    num2 = ft_printf(">%0.*d<\n",6, d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.1d<\n", d);
    num2 = ft_printf(">%0.1d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.2d<\n", d);
    num2 = ft_printf(">%0.2d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.3d<\n", d);
    num2 = ft_printf(">%0.3d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.4d<\n", d);
    num2 = ft_printf(">%0.4d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0.0d<\n", d);
    num2 = ft_printf(">%0.0d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.d<\n", d);
    num2 = ft_printf(">%1.d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.*d<\n",6, d);
    num2 = ft_printf(">%1.*d<\n",6, d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.1d<\n", d);
    num2 = ft_printf(">%1.1d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.2d<\n", d);
    num2 = ft_printf(">%1.2d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.3d<\n", d);
    num2 = ft_printf(">%1.3d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.4d<\n", d);
    num2 = ft_printf(">%1.4d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%1.0d<\n", d);
    num2 = ft_printf(">%1.0d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.d<\n", d);
    num2 = ft_printf(">%2.d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.*d<\n",6, d);
    num2 = ft_printf(">%2.*d<\n",6, d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.1d<\n", d);
    num2 = ft_printf(">%2.1d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.2d<\n", d);
    num2 = ft_printf(">%2.2d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.3d<\n", d);
    num2 = ft_printf(">%2.3d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.4d<\n", d);
    num2 = ft_printf(">%2.4d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%2.2d<\n", d);
    num2 = ft_printf(">%2.2d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.d<\n", d);
    num2 = ft_printf(">%3.d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.*d<\n",6, d);
    num2 = ft_printf(">%3.*d<\n",6, d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.1d<\n", d);
    num2 = ft_printf(">%3.1d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.2d<\n", d);
    num2 = ft_printf(">%3.2d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.3d<\n", d);
    num2 = ft_printf(">%3.3d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.4d<\n", d);
    num2 = ft_printf(">%3.4d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%3.2d<\n", d);
    num2 = ft_printf(">%3.2d<\n", d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.d<\n", d);
    num2 = ft_printf(">%4.d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.*d<\n",6, d);
    num2 = ft_printf(">%4.*d<\n",6, d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.1d<\n", d);
    num2 = ft_printf(">%4.1d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.2d<\n", d);
    num2 = ft_printf(">%4.2d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.3d<\n", d);
    num2 = ft_printf(">%4.3d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.4d<\n", d);
    num2 = ft_printf(">%4.4d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%4.0d<\n", d);
    num2 = ft_printf(">%4.0d<\n", d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.d<\n",10,d);
    num2 = ft_printf(">%0*.d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.*d<\n",10,6,d);
    num2 = ft_printf(">%0*.*d<\n",10,6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.0d<\n",10,d);
    num2 = ft_printf(">%0*.0d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.1d<\n",10,d);
    num2 = ft_printf(">%0*.1d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.2d<\n",10,d);
    num2 = ft_printf(">%0*.2d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.3d<\n",10,d);
    num2 = ft_printf(">%0*.3d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*.4d<\n",10,d);
    num2 = ft_printf(">%0*.4d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%0*d<\n",10,d);
    num2 = ft_printf(">%0*d<\n",10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.d<\n",d);
    num2 = ft_printf(">%00.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.*d<\n",6,d);
    num2 = ft_printf(">%00.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.0d<\n",d);
    num2 = ft_printf(">%00.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.1d<\n",d);
    num2 = ft_printf(">%00.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.2d<\n",d);
    num2 = ft_printf(">%00.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.3d<\n",d);
    num2 = ft_printf(">%00.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00.4d<\n",d);
    num2 = ft_printf(">%00.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%00d<\n",d);
    num2 = ft_printf(">%00d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.d<\n",d);
    num2 = ft_printf(">%01.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.*d<\n",6,d);
    num2 = ft_printf(">%01.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.0d<\n",d);
    num2 = ft_printf(">%01.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.1d<\n",d);
    num2 = ft_printf(">%01.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.2d<\n",d);
    num2 = ft_printf(">%01.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.3d<\n",d);
    num2 = ft_printf(">%01.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01.4d<\n",d);
    num2 = ft_printf(">%01.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%01d<\n",d);
    num2 = ft_printf(">%01d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.d<\n",d);
    num2 = ft_printf(">%02.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.*d<\n",6,d);
    num2 = ft_printf(">%02.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.0d<\n",d);
    num2 = ft_printf(">%02.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.1d<\n",d);
    num2 = ft_printf(">%02.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.2d<\n",d);
    num2 = ft_printf(">%02.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.3d<\n",d);
    num2 = ft_printf(">%02.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02.4d<\n",d);
    num2 = ft_printf(">%02.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%02d<\n",d);
    num2 = ft_printf(">%02d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.d<\n",d);
    num2 = ft_printf(">%03.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.*d<\n",6,d);
    num2 = ft_printf(">%03.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.0d<\n",d);
    num2 = ft_printf(">%03.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.1d<\n",d);
    num2 = ft_printf(">%03.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.2d<\n",d);
    num2 = ft_printf(">%03.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.3d<\n",d);
    num2 = ft_printf(">%03.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03.4d<\n",d);
    num2 = ft_printf(">%03.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%03d<\n",d);
    num2 = ft_printf(">%03d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.d<\n",d);
    num2 = ft_printf(">%04.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.*d<\n",6,d);
    num2 = ft_printf(">%04.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.0d<\n",d);
    num2 = ft_printf(">%04.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.1d<\n",d);
    num2 = ft_printf(">%04.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.2d<\n",d);
    num2 = ft_printf(">%04.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.3d<\n",d);
    num2 = ft_printf(">%04.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04.4d<\n",d);
    num2 = ft_printf(">%04.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%04d<\n",d);
    num2 = ft_printf(">%04d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.d<\n",d);
    num2 = ft_printf(">%--4.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.*d<\n",6,d);
    num2 = ft_printf(">%--4.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.0d<\n",d);
    num2 = ft_printf(">%--4.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.1d<\n",d);
    num2 = ft_printf(">%--4.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.2d<\n",d);
    num2 = ft_printf(">%--4.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.3d<\n",d);
    num2 = ft_printf(">%--4.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4.4d<\n",d);
    num2 = ft_printf(">%--4.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--4d<\n",d);
    num2 = ft_printf(">%--4d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.d<\n",d);
    num2 = ft_printf(">%--3.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.*d<\n",6,d);
    num2 = ft_printf(">%--3.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.0d<\n",d);
    num2 = ft_printf(">%--3.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.1d<\n",d);
    num2 = ft_printf(">%--3.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.2d<\n",d);
    num2 = ft_printf(">%--3.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.3d<\n",d);
    num2 = ft_printf(">%--3.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3.4d<\n",d);
    num2 = ft_printf(">%--3.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--3d<\n",d);
    num2 = ft_printf(">%--3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.d<\n",d);
    num2 = ft_printf(">%--2.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.*d<\n",6,d);
    num2 = ft_printf(">%--2.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.0d<\n",d);
    num2 = ft_printf(">%--2.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.1d<\n",d);
    num2 = ft_printf(">%--2.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.2d<\n",d);
    num2 = ft_printf(">%--2.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.3d<\n",d);
    num2 = ft_printf(">%--2.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2.4d<\n",d);
    num2 = ft_printf(">%--2.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--2d<\n",d);
    num2 = ft_printf(">%--2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.d<\n",d);
    num2 = ft_printf(">%--1.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.*d<\n",6,d);
    num2 = ft_printf(">%--1.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.0d<\n",d);
    num2 = ft_printf(">%--1.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.1d<\n",d);
    num2 = ft_printf(">%--1.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.2d<\n",d);
    num2 = ft_printf(">%--1.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.3d<\n",d);
    num2 = ft_printf(">%--1.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1.4d<\n",d);
    num2 = ft_printf(">%--1.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%--1d<\n",d);
    num2 = ft_printf(">%--1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.d<\n",d);
    num2 = ft_printf(">%-.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.*d<\n",6,d);
    num2 = ft_printf(">%-.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.0d<\n",d);
    num2 = ft_printf(">%-.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.1d<\n",d);
    num2 = ft_printf(">%-.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.2d<\n",d);
    num2 = ft_printf(">%-.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.3d<\n",d);
    num2 = ft_printf(">%-.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-.4d<\n",d);
    num2 = ft_printf(">%-.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-d<\n",d);
    num2 = ft_printf(">%-d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.d<\n",10,d);
    num2 = ft_printf(">%-*.d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.*d<\n",6,10,d);
    num2 = ft_printf(">%-*.*d<\n",6,10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.0d<\n",10,d);
    num2 = ft_printf(">%-*.0d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.1d<\n",10,d);
    num2 = ft_printf(">%-*.1d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.2d<\n",10,d);
    num2 = ft_printf(">%-*.2d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.3d<\n",10,d);
    num2 = ft_printf(">%-*.3d<\n",10,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*.4d<\n",10,d); // error(-)
    num2 = ft_printf(">%-*.4d<\n",10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-*d<\n",10,d);
    num2 = ft_printf(">%-*d<\n",10,d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.d<\n",d);
    num2 = ft_printf(">%-1.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.*d<\n",6,d);
    num2 = ft_printf(">%-1.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.0d<\n",d);
    num2 = ft_printf(">%-1.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.1d<\n",d);
    num2 = ft_printf(">%-1.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.2d<\n",d);
    num2 = ft_printf(">%-1.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.3d<\n",d);
    num2 = ft_printf(">%-1.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1.4d<\n",d);
    num2 = ft_printf(">%-1.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-1d<\n",d);
    num2 = ft_printf(">%-1d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.d<\n",d);
    num2 = ft_printf(">%-2.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.*d<\n",6,d);
    num2 = ft_printf(">%-2.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.0d<\n",d);
    num2 = ft_printf(">%-2.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.1d<\n",d);
    num2 = ft_printf(">%-2.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.2d<\n",d);
    num2 = ft_printf(">%-2.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.3d<\n",d);
    num2 = ft_printf(">%-2.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2.4d<\n",d);
    num2 = ft_printf(">%-2.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-2d<\n",d);
    num2 = ft_printf(">%-2d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.d<\n",d);
    num2 = ft_printf(">%-3.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.*d<\n",6,d);
    num2 = ft_printf(">%-3.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.0d<\n",d);
    num2 = ft_printf(">%-3.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.1d<\n",d);
    num2 = ft_printf(">%-3.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.2d<\n",d);
    num2 = ft_printf(">%-3.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.3d<\n",d);
    num2 = ft_printf(">%-3.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3.4d<\n",d);
    num2 = ft_printf(">%-3.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-3d<\n",d);
    num2 = ft_printf(">%-3d<\n",d);
    printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.d<\n",d);
    num2 = ft_printf(">%-4.d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.*d<\n",6,d);
    num2 = ft_printf(">%-4.*d<\n",6,d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.0d<\n",d);
    num2 = ft_printf(">%-4.0d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.1d<\n",d);
    num2 = ft_printf(">%-4.1d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.2d<\n",d);
    num2 = ft_printf(">%-4.2d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.3d<\n",d);
    num2 = ft_printf(">%-4.3d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    num1 = printf(">%-4.4d<\n",d);
    num2 = ft_printf(">%-4.4d<\n",d);
	printf("%d\n",num1);
    printf("%d\n",num2);
    printf("%d\n",printf("hello world"));
}